### ISSUE TITLE
Sentry Guns throw an exception

### ISSUE THREAD

**Issue by ghost** [wtfblub/NetspherePirates#11]
Leads to client crash

**Comment by BioAleks** [comment]
Client can use sentry guns, buy it, etc.
In weapon tutorial sentry guns working.
Only in multiplayer if client place sentry = client crash and delete this sentry.

**Comment by BioAleks** [comment]
Fixed by Huenato patch.

**Comment by BioAleks** [comment]
@wtfblub 
It's working ok in last build and turret kill count as a kill in table.
I create turret, destroy turret, kill with turret in multiplayer, kill turret by other player and no have any disconnect.
If kill turret - no add points in table. 
I don't remember if turret killed by another player game add him point for kill turret?

**Comment by wtfblub** [comment]
This is not fixed yet. The reason why it's not happening anymore is because i temporally removed the feature that was causing it.

**Comment by BioAleks** [comment]
@wtfblub For what this feature is need?
